language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    
before_script: 
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  
script:
  - mkdir -p build/logs
  #- vendor/bin/phpcs --standard=PSR2 src/
  # phpmd bug on trying to overwrite constant for hhvm
  #- vendor/bin/phpmd src/ xml codesize,controversial,design,naming,unusedcode
  #- vendor/bin/phpunit -v tests/SoundcloudTest.php
  - vendor/bin/phpunit -v -c phpunit.xml.dist
  
after_script:
  - php vendor/bin/coveralls -v
