language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
    
before_script: 
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mkdir -p build/logs
  
script:
  #- vendor/bin/phpcs --standard=PSR2 src/
  #- phpmd bug on trying to overwrite constant for hhvm
  #- vendor/bin/phpmd src/ xml codesize,controversial,design,naming,unusedcode
  - phpunit --verbose tests/AuthTest.php
  - phpunit --verbose tests/FactoryTest.php
  - phpunit --verbose tests/RequestTest.php
  - phpunit --verbose tests/ResourceTest.php
  - phpunit --verbose tests/ResponseTest.php
  - phpunit --verbose tests/UrlBuilderTest.php
  - phpunit --verbose tests/SoundcloudTest.php

  - phpunit -v -c phpunit.xml.dist --coverage-text
  
after_script:
  - php vendor/bin/coveralls -v
